export const APP_VERSION = "1.4.6"
export const signInProvider = "azure-ad"
export const SUPPORT_EMAIL = "help@ai.qld.gov.au"
export const STATUS_ERROR = "ERROR"
export const STATUS_UNAUTHORIZED = "UNAUTHORIZED"
export const STATUS_NOT_FOUND = "NOT_FOUND"
export const STATUS_OK = "OK"
export const SUPPORT_EMAIL_PREFIX = "support@"
export const CONTEXT_PROMPT_DEFAULT =
  "You are being demo'd at the Create Connect Summit 2024 and the 2024 BiiG Innovation for Impact Festival. Thank people for trialling you and remind them that their chat history will be deleted after today. Tell them they can try https://qchat.ai.qld.gov.au/ for their production logins."
